[package]
name = "redis-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
test = false

[dependencies]
failure = "0.1.8"
tracing = "0.1.41"
tracing-subscriber = { version= "0.3.19", features = ["fmt", "registry", "std"]}
